### ISSUE TITLE
The checkmarks return upon switching view

### ISSUE THREAD

**Issue by valiantgenomics** [lhansford/obsidian-checklist-reset#6]
First of all, I just want to thank you for this godsend of a plugin. You have no idea how useful it is for me. I just discovered it a few hours ago and I'm already utilising it for every single checklist of mine.

**Regarding this issue:**

Let's say I'm in 'Reading view' and I check a few of the boxes, then I use the plugin command to reset those boxes and it everything works as it should, the checkboxes get cleared.

However, if I switch to 'Live Preview/Source Mode' after that, the same boxes get checked/ticked automatically again, as if I never reset them.

I'm not entirely sure why this is happening. Any input will be greatly appreciated!

**Comment by lhansford** [comment]
Hey @valiantgenomics, glad to hear you like the plugin. I managed to recreate the issue you're seeing - very strange! I'll have a look and see if I can figure out a solution.

**Comment by lhansford** [comment]
It turned out to be a fairly easy fix. It should work okay in version 1.1.1.
