### ISSUE TITLE
Feature Request: Check all checklists

### ISSUE THREAD

**Issue by michaelzemba** [lhansford/obsidian-checklist-reset#7]
Thank you so much for this! I can't believe it's not a stock feature and I'm glad you made it happen.

Feature request: any chance of adding a command for the opposite -- checking all checklists in a document? Both are very handy for recurring task lists -- "Yes, I finished all this stuff" or "Yes, time to do all this again"

**Comment by lhansford** [comment]
Hey again @michaelzemba, that feature is now available in version 1.2.0
